---
name: Build and deploy documentation on merge to master

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'
      - 'requirements.docs.txt'
      - 'Dockerfile.docs'
      - 'mkdocs.yml'
      - 'CNAME' 
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'
      - 'requirements.docs.txt'
      - 'Dockerfile.docs'
      - 'mkdocs.yml'
      - 'CNAME'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kapitan recursively
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
      - run: pip install --upgrade pip && pip install -r requirements.docs.txt
      - run: mkdocs build
      - name: Deploy docs
        if: github.event_name != 'pull_request' && github.ref_name == github.event.repository.default_branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMITTER_NAME: mike-mkdocs-bot
          GIT_COMMITTER_EMAIL: admins@kapicorp
        run: mike deploy --push dev master
